# Generated by Django 4.2 on 2025-12-10 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('genre', models.CharField(max_length=100, verbose_name='Жанр')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='games/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('experience', models.IntegerField(default=0, verbose_name='Опыт')),
                ('total_points', models.IntegerField(default=0, verbose_name='Общие очки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Игрок',
                'verbose_name_plural': 'Игроки',
                'ordering': ['-level', '-experience'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('prize_pool', models.IntegerField(default=0, verbose_name='Призовой фонд')),
                ('status', models.CharField(choices=[('upcoming', 'Предстоящий'), ('active', 'Активный'), ('finished', 'Завершен')], default='upcoming', max_length=20, verbose_name='Статус')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('max_participants', models.IntegerField(default=100, verbose_name='Макс участников')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='games.game', verbose_name='Игра')),
                ('participants', models.ManyToManyField(blank=True, related_name='tournaments', to='games.player', verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.ImageField(upload_to='badges/', verbose_name='Иконка')),
                ('requirement', models.CharField(max_length=200, verbose_name='Требование')),
                ('players', models.ManyToManyField(related_name='badges', to='games.player', verbose_name='Игроки')),
            ],
            options={
                'verbose_name': 'Значок',
                'verbose_name_plural': 'Значки',
            },
        ),
        migrations.CreateModel(
            name='DailyQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('reward_points', models.IntegerField(default=50, verbose_name='Награда очков')),
                ('reward_experience', models.IntegerField(default=100, verbose_name='Награда опыта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='games.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Ежедневный квест',
                'verbose_name_plural': 'Ежедневные квесты',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('difficulty', models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='medium', max_length=10, verbose_name='Сложность')),
                ('points', models.IntegerField(default=10, verbose_name='Очки за достижение')),
                ('experience_reward', models.IntegerField(default=50, verbose_name='Награда опыта')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='achievements/', verbose_name='Иконка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='games.game', verbose_name='Игра')),
                ('players', models.ManyToManyField(blank=True, related_name='achievements', to='games.player', verbose_name='Игроки')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Позиция')),
                ('prize', models.IntegerField(default=0, verbose_name='Приз')),
                ('score', models.IntegerField(default=0, verbose_name='Очки')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_results', to='games.player', verbose_name='Игрок')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='games.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Результат турнира',
                'verbose_name_plural': 'Результаты турниров',
                'ordering': ['position'],
                'unique_together': {('tournament', 'player')},
            },
        ),
        migrations.CreateModel(
            name='PlayerQuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершен')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершен в')),
                ('progress', models.IntegerField(default=0, verbose_name='Прогресс (%)')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to='games.player', verbose_name='Игрок')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.dailyquest', verbose_name='Квест')),
            ],
            options={
                'verbose_name': 'Прогресс квеста',
                'verbose_name_plural': 'Прогресс квестов',
                'unique_together': {('player', 'quest')},
            },
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_played', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Часов сыграно')),
                ('game_level', models.IntegerField(default=1, verbose_name='Уровень в игре')),
                ('game_points', models.IntegerField(default=0, verbose_name='Очки в игре')),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='games.game', verbose_name='Игра')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Прогресс игрока',
                'verbose_name_plural': 'Прогресс игроков',
                'ordering': ['-last_played'],
                'unique_together': {('player', 'game')},
            },
        ),
        migrations.CreateModel(
            name='GameReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст рецензии')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.game', verbose_name='Игра')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='games.player', verbose_name='Игрок')),
            ],
            options={
                'verbose_name': 'Рецензия',
                'verbose_name_plural': 'Рецензии',
                'ordering': ['-created_at'],
                'unique_together': {('game', 'player')},
            },
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидание'), ('accepted', 'Принята'), ('declined', 'Отклонена')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='games.player', verbose_name='От')),
                ('to_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='games.player', verbose_name='К')),
            ],
            options={
                'verbose_name': 'Заявка в друзья',
                'verbose_name_plural': 'Заявки в друзья',
                'unique_together': {('from_player', 'to_player')},
            },
        ),
    ]
